OPSMN-6523: Spit out relevant error when registration lookup details are missing from the input request of the update API.
Error: Registration lookup details not specified. Either one of these field values need to be specified - Registration ID or CP short title & PPID or CP short title & eMPI.